### PR TITLE
Added ps1 script for Windows, edited .sh for UNIX

### PR DESCRIPTION
**Pull request by office-chair**
This is for running on Windows and UNIX.

To run on Ubuntu all that was needed was to prepend relative paths with `.`. That should not create any problems on Mac.

To run on Windows, you can either run the .ps1 script or use [wsl](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and run the .sh script from there like you would on UNIX.

### CODE REVIEW

**Comment by SeaCelo** [comment]
I’ll test the .sh to make sure the paths work. For the ps1 script, it is using the old structure. The new script hardcodes the model and all paths. Can you update to use that structure?

**Comment by SeaCelo** [comment]
I’m also going to test using the ./ at the beginning of the path to call mallet, instead of creating the $parent _path. This should simplify things more.

**Comment by office-chair** [comment]
The ps1 script hardcodes everything too, it just uses variables in some repeated places. I've tested with new structure, and it was working.

I will get rid of variables though.

**Comment by office-chair** [comment]
Oh, if you're referring to the `Get-Location` and `Set-Location $env:MALLET_HOME` parts, that's because installation is different for Windows. The script presumes that the mallet dir is in path and the `MALLET_HOME` path variable is set to the mallet dir.

While for UNIX and Mac I think you can just place the mallet dir into the project dir

**Comment by office-chair** [comment]
>While for UNIX and Mac I think you can just place the mallet dir into the project dir

Just tested it, and it turns out you can do that on Windows too. Will update the pr with everything hardcoded for ps1.

**Comment by SeaCelo** [comment]
Great. We can’t assume that mallet will be added to the path. See the news ReadMe. We actually have the user download Mallet into the directory as part of the installation, but we don’t mess with $PATH. Maybe there is a batter way, but this solves the common denominator problem.

**Comment by office-chair** [comment]
I get a `./target/output/scores-out.txt (No such file or directory)` error on both Linux and Windows unless there's an `output` folder. Turns our git can't push empty folders (hence why it wasn't tracked before), so I pushed one with a .gitignore file.

**Pull request merged**
